In [12]:
x = random.randint(0,100)
print(x)

21


In [14]:
# random array
from numpy import random
x = random.randint(0,100,size=5)
print(x)

[51  7 88 74 37]


In [16]:
import numpy as np
a=np.array([1,2,3,4])
print(a[2]+a[3])

7


In [18]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
print(arr[1,3])

9


In [20]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [21]:
print(a[0,1,2])

6
