In [2]:
# accessing array elements using numpy
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[0])
print(arr[4])


1
5


In [23]:
# 2D array
# [1,2,3]
# [4,5,6]
arr2=np.array([[1,2,3],
               [4,5,6]])
arr3=np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
               [10,11,12]])
print(arr2)


[[1 2 3]
 [4 5 6]]


In [15]:
print(arr2[0][0])

1


In [16]:
print(arr2[0][1])

2


In [17]:
print(arr2[0][2])

3


In [18]:
print(arr2[1][0])

4


In [19]:
print(arr2[1][1])

5


In [20]:
print(arr2[1][2])

6


In [21]:
# n dimenssion to find dimenssion of an array
print(arr.ndim)

1


In [22]:
print(arr2.ndim)

2


In [24]:
print(arr3.ndim)

2


In [28]:
# negative indexing
a = np.array([1,2,3,4,5,6])
print(a[0])
print(a[2])
print(a[4])
print(a[-1]) # last ele
print(a[-2]) # last 2nd ele

1
3
5
6
5


In [29]:
print(arr3[-1][0])

10


In [30]:
print(arr3[-1][-1])

12


In [31]:
print(arr3[0][-1])

3


In [32]:
print(arr3[2:])

[[ 7  8  9]
 [10 11 12]]


In [33]:
print(arr3[3:])

[[10 11 12]]


In [34]:
print(arr[:])

[1 2 3 4 5 6 7 8]


In [36]:
# identify data types of an array
print(arr.dtype)

int32


In [37]:
# iterating is same as list

<U1


In [38]:
print(arr3.shape)

(4, 3)


In [42]:
arr4=arr3.reshape(3,4)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [43]:
print(arr4.shape)

(3, 4)


In [44]:
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
# joining 2 array using join 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [49]:
# slpiting arrays
a=np.array_split(arr,3)

In [50]:
print(a)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [51]:
a=np.array([1,5,7,8,2,13,17,12,11,])
print(np.sort(a))

[ 1  2  5  7  8 11 12 13 17]
